USE [iiiTravel]
GO

/****** Object:  Trigger [dbo].[T_SPOT_LIKE_RECORD]    Script Date: 2014/9/8 ¤U¤È 07:49:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[T_SPOT_LIKE_RECORD] 
   ON  [dbo].[SPOT_LIKE_RECORD]
   AFTER UPDATE, INSERT, DELETE
AS 
BEGIN
	SET NOCOUNT ON;
	DECLARE @SPOT_ID VARCHAR(11)
	
	-- INSERT
	IF EXISTS(SELECT * FROM INSERTED)
	BEGIN
		SELECT @SPOT_ID = INSERTED.SPOT_ID FROM INSERTED
		UPDATE SPOT_DETAIL SET LIKE_COUNT = ISNULL(LIKE_COUNT,0) + 1
		WHERE SPOT_ID = @SPOT_ID
	END
	
	IF EXISTS(SELECT * FROM DELETED)
	BEGIN
		SELECT @SPOT_ID = DELETED.SPOT_ID FROM DELETED
		UPDATE SPOT_DETAIL SET LIKE_COUNT = LIKE_COUNT - 1
		WHERE SPOT_ID = @SPOT_ID
	END
END





GO


