package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private String accountId;
	private String email;
	private String password;
	private String nickname;
	private Integer accountLevel;
	private Date lastLogonDt;
	private byte[] image;
	private Integer blacklistLevel;
	private Set<Trip> trips = new HashSet<Trip>(0);
	private Set<SpotDetail> spotDetails = new HashSet<SpotDetail>(0);
	private Set<SpotCommentRecord> spotCommentRecords = new HashSet<SpotCommentRecord>(
			0);
	private Set<SpotDetail> spotDetails_1 = new HashSet<SpotDetail>(0);
	private SpotOwner spotOwner;
	private Set<Trip> trips_1 = new HashSet<Trip>(0);
	private Set<Trip> trips_2 = new HashSet<Trip>(0);
	private Set<Trip> trips_3 = new HashSet<Trip>(0);
	private Set<SpotDetail> spotDetails_2 = new HashSet<SpotDetail>(0);

	public Account() {
	}
	
	@Override
	public String toString() {
		return "AccountId:"+accountId+"; Email:"+email+"; Password:"+password+"; Nickname:"+nickname+"AccountLevel:"+accountLevel+"; LastLoginDate:"+lastLogonDt+"; BlacklistLevel:"+blacklistLevel;
	}

	public Account(String accountId, String email, String password,
			String nickname) {
		this.accountId = accountId;
		this.email = email;
		this.password = password;
		this.nickname = nickname;
	}

	public Account(String accountId, String email, String password,
			String nickname, Integer accountLevel, Date lastLogonDt,
			byte[] image, Integer blacklistLevel, Set<Trip> trips,
			Set<SpotDetail> spotDetails,
			Set<SpotCommentRecord> spotCommentRecords,
			Set<SpotDetail> spotDetails_1, SpotOwner spotOwner,
			Set<Trip> trips_1, Set<Trip> trips_2, Set<Trip> trips_3,
			Set<SpotDetail> spotDetails_2) {
		this.accountId = accountId;
		this.email = email;
		this.password = password;
		this.nickname = nickname;
		this.accountLevel = accountLevel;
		this.lastLogonDt = lastLogonDt;
		this.image = image;
		this.blacklistLevel = blacklistLevel;
		this.trips = trips;
		this.spotDetails = spotDetails;
		this.spotCommentRecords = spotCommentRecords;
		this.spotDetails_1 = spotDetails_1;
		this.spotOwner = spotOwner;
		this.trips_1 = trips_1;
		this.trips_2 = trips_2;
		this.trips_3 = trips_3;
		this.spotDetails_2 = spotDetails_2;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public Integer getAccountLevel() {
		return this.accountLevel;
	}

	public void setAccountLevel(Integer accountLevel) {
		this.accountLevel = accountLevel;
	}

	public Date getLastLogonDt() {
		return this.lastLogonDt;
	}

	public void setLastLogonDt(Date lastLogonDt) {
		this.lastLogonDt = lastLogonDt;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Integer getBlacklistLevel() {
		return this.blacklistLevel;
	}

	public void setBlacklistLevel(Integer blacklistLevel) {
		this.blacklistLevel = blacklistLevel;
	}

	public Set<Trip> getTrips() {
		return this.trips;
	}

	public void setTrips(Set<Trip> trips) {
		this.trips = trips;
	}

	public Set<SpotDetail> getSpotDetails() {
		return this.spotDetails;
	}

	public void setSpotDetails(Set<SpotDetail> spotDetails) {
		this.spotDetails = spotDetails;
	}

	public Set<SpotCommentRecord> getSpotCommentRecords() {
		return this.spotCommentRecords;
	}

	public void setSpotCommentRecords(Set<SpotCommentRecord> spotCommentRecords) {
		this.spotCommentRecords = spotCommentRecords;
	}

	public Set<SpotDetail> getSpotDetails_1() {
		return this.spotDetails_1;
	}

	public void setSpotDetails_1(Set<SpotDetail> spotDetails_1) {
		this.spotDetails_1 = spotDetails_1;
	}

	public SpotOwner getSpotOwner() {
		return this.spotOwner;
	}

	public void setSpotOwner(SpotOwner spotOwner) {
		this.spotOwner = spotOwner;
	}

	public Set<Trip> getTrips_1() {
		return this.trips_1;
	}

	public void setTrips_1(Set<Trip> trips_1) {
		this.trips_1 = trips_1;
	}

	public Set<Trip> getTrips_2() {
		return this.trips_2;
	}

	public void setTrips_2(Set<Trip> trips_2) {
		this.trips_2 = trips_2;
	}

	public Set<Trip> getTrips_3() {
		return this.trips_3;
	}

	public void setTrips_3(Set<Trip> trips_3) {
		this.trips_3 = trips_3;
	}

	public Set<SpotDetail> getSpotDetails_2() {
		return this.spotDetails_2;
	}

	public void setSpotDetails_2(Set<SpotDetail> spotDetails_2) {
		this.spotDetails_2 = spotDetails_2;
	}

}
