package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Ad generated by hbm2java
 */
@Entity
@Table(name = "AD", schema = "dbo", catalog = "iiiTravel")
public class Ad implements java.io.Serializable {

	private String adId;
	private SpotDetail spotDetail;
	private Date validDay;
	private byte[] adImg;
	private String tempAdId;

	public Ad() {
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return adId+", "+spotDetail.getSpotId()+", "+validDay;
	}
	public Ad(SpotDetail spotDetail, Date validDay, String tempAdId) {
		this.spotDetail = spotDetail;
		this.validDay = validDay;
		this.tempAdId = tempAdId;
	}

	public Ad(SpotDetail spotDetail, Date validDay, byte[] adImg,
			String tempAdId) {
		this.spotDetail = spotDetail;
		this.validDay = validDay;
		this.adImg = adImg;
		this.tempAdId = tempAdId;
	}

	@GenericGenerator(name = "generator", strategy = "select", parameters = @Parameter(name = "key", value = "tempAdId"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "AD_ID", nullable = false, length = 8)
	public String getAdId() {
		return this.adId;
	}

	public void setAdId(String adId) {
		this.adId = adId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SPOT_ID", nullable = false)
	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_DAY", nullable = false, length = 10)
	public Date getValidDay() {
		return this.validDay;
	}

	public void setValidDay(Date validDay) {
		this.validDay = validDay;
	}

	@Column(name = "AD_IMG")
	public byte[] getAdImg() {
		return this.adImg;
	}

	public void setAdImg(byte[] adImg) {
		this.adImg = adImg;
	}

	@Column(name = "TEMP_AD_ID", unique = true, nullable = false, length = 8)
	public String getTempAdId() {
		return this.tempAdId;
	}

	public void setTempAdId(String tempAdId) {
		this.tempAdId = tempAdId;
	}

}
