package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Coupons generated by hbm2java
 */
@Entity
@Table(name = "COUPONS", schema = "dbo", catalog = "iiiTravel")
public class Coupons implements java.io.Serializable {

	private String couponId;
	private SpotDetail spotDetail;
	private byte[] couponImg;
	private String couponDescription;
	private Date validDay;
	private String tempCouponId;

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return couponId+", "+spotDetail.getSpotId()+", "+validDay+", "+couponDescription;
	}
	public Coupons() {
	}

	public Coupons(SpotDetail spotDetail, Date validDay, String tempCouponId) {
		this.spotDetail = spotDetail;
		this.validDay = validDay;
		this.tempCouponId = tempCouponId;
	}

	public Coupons(SpotDetail spotDetail, byte[] couponImg,
			String couponDescription, Date validDay, String tempCouponId) {
		this.spotDetail = spotDetail;
		this.couponImg = couponImg;
		this.couponDescription = couponDescription;
		this.validDay = validDay;
		this.tempCouponId = tempCouponId;
	}

	@GenericGenerator(name = "generator", strategy = "select", parameters = @Parameter(name = "key", value = "tempCouponId"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COUPON_ID", nullable = false, length = 8)
	public String getCouponId() {
		return this.couponId;
	}

	public void setCouponId(String couponId) {
		this.couponId = couponId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPOT_ID", nullable = false)
	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	@Column(name = "COUPON_IMG")
	public byte[] getCouponImg() {
		return this.couponImg;
	}

	public void setCouponImg(byte[] couponImg) {
		this.couponImg = couponImg;
	}

	@Column(name = "COUPON_DESCRIPTION")
	public String getCouponDescription() {
		return this.couponDescription;
	}

	public void setCouponDescription(String couponDescription) {
		this.couponDescription = couponDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_DAY", nullable = false, length = 10)
	public Date getValidDay() {
		return this.validDay;
	}

	public void setValidDay(Date validDay) {
		this.validDay = validDay;
	}

	@Column(name = "TEMP_COUPON_ID", unique = true, nullable = false, length = 8)
	public String getTempCouponId() {
		return this.tempCouponId;
	}

	public void setTempCouponId(String tempCouponId) {
		this.tempCouponId = tempCouponId;
	}

}
