package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * SpotCollectRecord generated by hbm2java
 */
public class SpotCollectRecord implements java.io.Serializable {

	private SpotCollectRecordId id;

	public SpotCollectRecord() {
	}

	public SpotCollectRecord(SpotCollectRecordId id) {
		this.id = id;
	}

	public SpotCollectRecordId getId() {
		return this.id;
	}

	public void setId(SpotCollectRecordId id) {
		this.id = id;
	}

}
