package model;

// Generated 2014/9/4 �U�� 08:08:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SpotImg generated by hbm2java
 */
public class SpotImg implements java.io.Serializable {

	private String imgId;
	private String spotId;
	private SpotDetail spotDetail;
	private byte[] spotImg;
	private Integer imgOrder;
	private String tempImgId;
	private Set<TripDetail> tripDetails = new HashSet<TripDetail>(0);

	public SpotImg() {
	}

	public SpotImg(String spotId, SpotDetail spotDetail, String tempImgId) {
		this.spotId = spotId;
		this.spotDetail = spotDetail;
		this.tempImgId = tempImgId;
	}

	public SpotImg(String spotId, SpotDetail spotDetail, byte[] spotImg,
			Integer imgOrder, String tempImgId, Set<TripDetail> tripDetails) {
		this.spotId = spotId;
		this.spotDetail = spotDetail;
		this.spotImg = spotImg;
		this.imgOrder = imgOrder;
		this.tempImgId = tempImgId;
		this.tripDetails = tripDetails;
	}

	public String getImgId() {
		return this.imgId;
	}

	public void setImgId(String imgId) {
		this.imgId = imgId;
	}

	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	public byte[] getSpotImg() {
		return this.spotImg;
	}

	public void setSpotImg(byte[] spotImg) {
		this.spotImg = spotImg;
	}

	public Integer getImgOrder() {
		return this.imgOrder;
	}

	public void setImgOrder(Integer imgOrder) {
		this.imgOrder = imgOrder;
	}

	public String getTempImgId() {
		return this.tempImgId;
	}

	public void setTempImgId(String tempImgId) {
		this.tempImgId = tempImgId;
	}

	public Set<TripDetail> getTripDetails() {
		return this.tripDetails;
	}

	public void setTripDetails(Set<TripDetail> tripDetails) {
		this.tripDetails = tripDetails;
	}

}
