package model;

// Generated 2014/9/11 �U�� 09:48:57 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SpotCommentRecord generated by hbm2java
 */
public class SpotCommentRecord implements java.io.Serializable {

	private String commentId;
	private String accountId;
	private String spotId;
	private String comment;
	private Date cmtDt;
	private String tempCommentId;

	public SpotCommentRecord() {
	}

	public SpotCommentRecord(String commentId, String accountId, String spotId,
			String comment, Date cmtDt, String tempCommentId) {
		this.commentId = commentId;
		this.accountId = accountId;
		this.spotId = spotId;
		this.comment = comment;
		this.cmtDt = cmtDt;
		this.tempCommentId = tempCommentId;
	}

	public String getCommentId() {
		return this.commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCmtDt() {
		return this.cmtDt;
	}

	public void setCmtDt(Date cmtDt) {
		this.cmtDt = cmtDt;
	}

	public String getTempCommentId() {
		return this.tempCommentId;
	}

	public void setTempCommentId(String tempCommentId) {
		this.tempCommentId = tempCommentId;
	}

}
