package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * SpotLikeRecord generated by hbm2java
 */
public class SpotLikeRecord implements java.io.Serializable {

	private SpotLikeRecordId id;

	public SpotLikeRecord() {
	}

	public SpotLikeRecord(SpotLikeRecordId id) {
		this.id = id;
	}

	public SpotLikeRecordId getId() {
		return this.id;
	}

	public void setId(SpotLikeRecordId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		
		
		return id.toString();
	}

	

}
