package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SpotOwner generated by hbm2java
 */
@Entity
@Table(name = "SPOT_OWNER", schema = "dbo", catalog = "iiiTravel")
public class SpotOwner implements java.io.Serializable {

	private String accountId;
	private String ownerName;

	public SpotOwner() {
	}

	@Override
	public String toString() {
		return "AccountId="+accountId+"; OwnerName="+ownerName;
	}

	public SpotOwner(String accountId) {
		this.accountId = accountId;
	}

	public SpotOwner(String accountId, String ownerName) {
		this.accountId = accountId;
		this.ownerName = ownerName;
	}

	@Id
	@Column(name = "ACCOUNT_ID", nullable = false, length = 9)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "OWNER_NAME", length = 50)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

}
