package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trip generated by hbm2java
 */
public class Trip implements java.io.Serializable {

	private String tripId;
	private Account account;
	private String tripName;
	private Integer totalDay;
	private Date startDate;
	private Integer likeCount;
	private String tempTripId;
	private Set<Account> accounts = new HashSet<Account>(0);
	private Set<TripDetail> tripDetails = new HashSet<TripDetail>(0);
	private Set<Account> accounts_1 = new HashSet<Account>(0);

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return tripId+", "+tripName+", "+startDate+", "+likeCount;
	}

	public Trip() {
	}

	public Trip(String tripId, Account account, Date startDate,
			String tempTripId) {
		this.tripId = tripId;
		this.account = account;
		this.startDate = startDate;
		this.tempTripId = tempTripId;
	}

	public Trip(String tripId, Account account, String tripName,
			Integer totalDay, Date startDate, Integer likeCount,
			String tempTripId, Set<Account> accounts,
			Set<TripDetail> tripDetails, Set<Account> accounts_1) {
		this.tripId = tripId;
		this.account = account;
		this.tripName = tripName;
		this.totalDay = totalDay;
		this.startDate = startDate;
		this.likeCount = likeCount;
		this.tempTripId = tempTripId;
		this.accounts = accounts;
		this.tripDetails = tripDetails;
		this.accounts_1 = accounts_1;
	}

	public String getTripId() {
		return this.tripId;
	}

	public void setTripId(String tripId) {
		this.tripId = tripId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getTripName() {
		return this.tripName;
	}

	public void setTripName(String tripName) {
		this.tripName = tripName;
	}

	public Integer getTotalDay() {
		return this.totalDay;
	}

	public void setTotalDay(Integer totalDay) {
		this.totalDay = totalDay;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Integer getLikeCount() {
		return this.likeCount;
	}

	public void setLikeCount(Integer likeCount) {
		this.likeCount = likeCount;
	}

	public String getTempTripId() {
		return this.tempTripId;
	}

	public void setTempTripId(String tempTripId) {
		this.tempTripId = tempTripId;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

	public Set<TripDetail> getTripDetails() {
		return this.tripDetails;
	}

	public void setTripDetails(Set<TripDetail> tripDetails) {
		this.tripDetails = tripDetails;
	}

	public Set<Account> getAccounts_1() {
		return this.accounts_1;
	}

	public void setAccounts_1(Set<Account> accounts_1) {
		this.accounts_1 = accounts_1;
	}

}
