package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * TripDetail generated by hbm2java
 */
public class TripDetail implements java.io.Serializable {

	private String tripDetailId;
	private SpotDetail spotDetail;
	private SpotImg spotImg;
	private Trip trip;
	private Integer tripDayOrder;
	private String tripDescription;
	private double stayTime;
	private int spotOrder;
	private String tempTripDetailId;

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return tripDetailId+", "+spotDetail.getSpotId()+", "+stayTime+", "+spotOrder;
	}

	public TripDetail() {
	}

	public TripDetail(String tripDetailId, SpotDetail spotDetail,
			SpotImg spotImg, Trip trip, double stayTime, int spotOrder,
			String tempTripDetailId) {
		this.tripDetailId = tripDetailId;
		this.spotDetail = spotDetail;
		this.spotImg = spotImg;
		this.trip = trip;
		this.stayTime = stayTime;
		this.spotOrder = spotOrder;
		this.tempTripDetailId = tempTripDetailId;
	}

	public TripDetail(String tripDetailId, SpotDetail spotDetail,
			SpotImg spotImg, Trip trip, Integer tripDayOrder,
			String tripDescription, double stayTime, int spotOrder,
			String tempTripDetailId) {
		this.tripDetailId = tripDetailId;
		this.spotDetail = spotDetail;
		this.spotImg = spotImg;
		this.trip = trip;
		this.tripDayOrder = tripDayOrder;
		this.tripDescription = tripDescription;
		this.stayTime = stayTime;
		this.spotOrder = spotOrder;
		this.tempTripDetailId = tempTripDetailId;
	}

	public String getTripDetailId() {
		return this.tripDetailId;
	}

	public void setTripDetailId(String tripDetailId) {
		this.tripDetailId = tripDetailId;
	}

	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	public SpotImg getSpotImg() {
		return this.spotImg;
	}

	public void setSpotImg(SpotImg spotImg) {
		this.spotImg = spotImg;
	}

	public Trip getTrip() {
		return this.trip;
	}

	public void setTrip(Trip trip) {
		this.trip = trip;
	}

	public Integer getTripDayOrder() {
		return this.tripDayOrder;
	}

	public void setTripDayOrder(Integer tripDayOrder) {
		this.tripDayOrder = tripDayOrder;
	}

	public String getTripDescription() {
		return this.tripDescription;
	}

	public void setTripDescription(String tripDescription) {
		this.tripDescription = tripDescription;
	}

	public double getStayTime() {
		return this.stayTime;
	}

	public void setStayTime(double stayTime) {
		this.stayTime = stayTime;
	}

	public int getSpotOrder() {
		return this.spotOrder;
	}

	public void setSpotOrder(int spotOrder) {
		this.spotOrder = spotOrder;
	}

	public String getTempTripDetailId() {
		return this.tempTripDetailId;
	}

	public void setTempTripDetailId(String tempTripDetailId) {
		this.tempTripDetailId = tempTripDetailId;
	}

}
