package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Coupons generated by hbm2java
 */
public class Coupons implements java.io.Serializable {

	private String couponId;
	private SpotDetail spotDetail;
	private byte[] couponImg;
	private String couponDescription;
	private Date validDay;
	private String tempCouponId;

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return couponId+", "+spotDetail.getSpotId()+", "+validDay+", "+couponDescription;
	}

	public Coupons() {
	}

	public Coupons(String couponId, SpotDetail spotDetail, Date validDay,
			String tempCouponId) {
		this.couponId = couponId;
		this.spotDetail = spotDetail;
		this.validDay = validDay;
		this.tempCouponId = tempCouponId;
	}

	public Coupons(String couponId, SpotDetail spotDetail, byte[] couponImg,
			String couponDescription, Date validDay, String tempCouponId) {
		this.couponId = couponId;
		this.spotDetail = spotDetail;
		this.couponImg = couponImg;
		this.couponDescription = couponDescription;
		this.validDay = validDay;
		this.tempCouponId = tempCouponId;
	}

	public String getCouponId() {
		return this.couponId;
	}

	public void setCouponId(String couponId) {
		this.couponId = couponId;
	}

	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	public byte[] getCouponImg() {
		return this.couponImg;
	}

	public void setCouponImg(byte[] couponImg) {
		this.couponImg = couponImg;
	}

	public String getCouponDescription() {
		return this.couponDescription;
	}

	public void setCouponDescription(String couponDescription) {
		this.couponDescription = couponDescription;
	}

	public Date getValidDay() {
		return this.validDay;
	}

	public void setValidDay(Date validDay) {
		this.validDay = validDay;
	}

	public String getTempCouponId() {
		return this.tempCouponId;
	}

	public void setTempCouponId(String tempCouponId) {
		this.tempCouponId = tempCouponId;
	}

}
