package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SpotCommentRecord generated by hbm2java
 */
public class SpotCommentRecord implements java.io.Serializable {

	private SpotCommentRecordId id;
	private Account account;
	private SpotDetail spotDetail;
	private String comment;
	private Date cmtDt;
	private String tempCommentId;

	public SpotCommentRecord() {
	}

	public SpotCommentRecord(SpotCommentRecordId id, Account account,
			SpotDetail spotDetail, String comment, Date cmtDt,
			String tempCommentId) {
		this.id = id;
		this.account = account;
		this.spotDetail = spotDetail;
		this.comment = comment;
		this.cmtDt = cmtDt;
		this.tempCommentId = tempCommentId;
	}

	public SpotCommentRecordId getId() {
		return this.id;
	}

	public void setId(SpotCommentRecordId id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCmtDt() {
		return this.cmtDt;
	}

	public void setCmtDt(Date cmtDt) {
		this.cmtDt = cmtDt;
	}

	public String getTempCommentId() {
		return this.tempCommentId;
	}

	public void setTempCommentId(String tempCommentId) {
		this.tempCommentId = tempCommentId;
	}

}
