package model;

// Generated 2014/9/11 �U�� 09:48:57 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SpotCommentRecord generated by hbm2java
 */
@Entity
@Table(name = "SPOT_COMMENT_RECORD", schema = "dbo", catalog = "iiiTravel")
public class SpotCommentRecord implements java.io.Serializable {

	private String commentId;
	private String accountId;
	private String spotId;
	private String comment;
	private Date cmtDt;
	private String tempCommentId;

	public SpotCommentRecord() {
	}

	public SpotCommentRecord(String accountId, String spotId, String comment,
			Date cmtDt, String tempCommentId) {
		this.accountId = accountId;
		this.spotId = spotId;
		this.comment = comment;
		this.cmtDt = cmtDt;
		this.tempCommentId = tempCommentId;
	}

	@GenericGenerator(name = "generator", strategy = "select", parameters = @Parameter(name = "key", value = "tempCommentId"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COMMENT_ID", nullable = false, length = 12)
	public String getCommentId() {
		return this.commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, length = 9)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "SPOT_ID", nullable = false, length = 11)
	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	@Column(name = "COMMENT", nullable = false)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CMT_DT", nullable = false, length = 10)
	public Date getCmtDt() {
		return this.cmtDt;
	}

	public void setCmtDt(Date cmtDt) {
		this.cmtDt = cmtDt;
	}

	@Column(name = "TEMP_COMMENT_ID", unique = true, nullable = false, length = 12)
	public String getTempCommentId() {
		return this.tempCommentId;
	}

	public void setTempCommentId(String tempCommentId) {
		this.tempCommentId = tempCommentId;
	}

	@Override
	public String toString() {
		
		return " [commentId: "+commentId+",comment: "+comment+"]";
	}

	
}
