package model;

// Generated 2014/9/4 �U�� 08:08:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SpotImg generated by hbm2java
 */
@Entity
@Table(name = "SPOT_IMG", schema = "dbo", catalog = "iiiTravel")
public class SpotImg implements java.io.Serializable {

	private String imgId;
	private String spotId;
	private SpotDetail spotDetail;
	private byte[] spotImg;
	private Integer imgOrder;
	private String tempImgId;
	private Set<TripDetail> tripDetails = new HashSet<TripDetail>(0);

	public SpotImg() {
	}

	public SpotImg(String spotId, SpotDetail spotDetail, String tempImgId) {
		this.spotId = spotId;
		this.spotDetail = spotDetail;
		this.tempImgId = tempImgId;
	}

	public SpotImg(String spotId, SpotDetail spotDetail, byte[] spotImg,
			Integer imgOrder, String tempImgId, Set<TripDetail> tripDetails) {
		this.spotId = spotId;
		this.spotDetail = spotDetail;
		this.spotImg = spotImg;
		this.imgOrder = imgOrder;
		this.tempImgId = tempImgId;
		this.tripDetails = tripDetails;
	}

	@GenericGenerator(name = "generator", strategy = "select", parameters = @Parameter(name = "key", value = "tempImgId"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "IMG_ID", nullable = false, length = 11)
	public String getImgId() {
		return this.imgId;
	}

	public void setImgId(String imgId) {
		this.imgId = imgId;
	}

	@Column(name = "SPOT_ID", nullable = false, length = 11)
	public String getSpotId() {
		return this.spotId;
	}

	public void setSpotId(String spotId) {
		this.spotId = spotId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPOT_ID", nullable = false, insertable = false, updatable = false)
	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	@Column(name = "SPOT_IMG")
	public byte[] getSpotImg() {
		return this.spotImg;
	}

	public void setSpotImg(byte[] spotImg) {
		this.spotImg = spotImg;
	}

	@Column(name = "IMG_ORDER")
	public Integer getImgOrder() {
		return this.imgOrder;
	}

	public void setImgOrder(Integer imgOrder) {
		this.imgOrder = imgOrder;
	}

	@Column(name = "TEMP_IMG_ID", unique = true, nullable = false, length = 11)
	public String getTempImgId() {
		return this.tempImgId;
	}

	public void setTempImgId(String tempImgId) {
		this.tempImgId = tempImgId;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name="IMG_ID", updatable = false)
	public Set<TripDetail> getTripDetails() {
		return this.tripDetails;
	}

	public void setTripDetails(Set<TripDetail> tripDetails) {
		this.tripDetails = tripDetails;
	}

}
