package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * SpotOwner generated by hbm2java
 */
public class SpotOwner implements java.io.Serializable {

	private String accountId;
	private Account account;
	private String ownerName;

	public SpotOwner() {
	}

	public SpotOwner(Account account) {
		this.account = account;
	}

	public SpotOwner(Account account, String ownerName) {
		this.account = account;
		this.ownerName = ownerName;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

}
