package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TripDetail generated by hbm2java
 */
@Entity
@Table(name = "TRIP_DETAIL", schema = "dbo", catalog = "iiiTravel")
public class TripDetail implements java.io.Serializable {

	private String tripDetailId;
	private SpotDetail spotDetail;
	private Trip trip;
	private Integer tripDayOrder;
	private String tripDescription;
	private double stayTime;
	private int spotOrder;
	private String tempTripDetailId;

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return tripDetailId + ", " + spotDetail.getSpotId() + ", " + stayTime
				+ ", " + spotOrder+", " + tripDayOrder;
	}
	public TripDetail() {
	}

	public TripDetail(Trip trip, double stayTime, int spotOrder,
			String tempTripDetailId) {
		this.trip = trip;
		this.stayTime = stayTime;
		this.spotOrder = spotOrder;
		this.tempTripDetailId = tempTripDetailId;
	}

	public TripDetail(SpotDetail spotDetail, Trip trip, Integer tripDayOrder,
			String tripDescription, double stayTime, int spotOrder,
			String tempTripDetailId) {
		this.spotDetail = spotDetail;
		this.trip = trip;
		this.tripDayOrder = tripDayOrder;
		this.tripDescription = tripDescription;
		this.stayTime = stayTime;
		this.spotOrder = spotOrder;
		this.tempTripDetailId = tempTripDetailId;
	}

	@GenericGenerator(name = "generator", strategy = "select", parameters = @Parameter(name = "key", value = "tempTripDetailId"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "TRIP_DETAIL_ID", nullable = false, length = 10)
	public String getTripDetailId() {
		return this.tripDetailId;
	}

	public void setTripDetailId(String tripDetailId) {
		this.tripDetailId = tripDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPOT_ID")
	public SpotDetail getSpotDetail() {
		return this.spotDetail;
	}

	public void setSpotDetail(SpotDetail spotDetail) {
		this.spotDetail = spotDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRIP_ID", nullable = false)
	public Trip getTrip() {
		return this.trip;
	}

	public void setTrip(Trip trip) {
		this.trip = trip;
	}

	@Column(name = "TRIP_DAY_ORDER")
	public Integer getTripDayOrder() {
		return this.tripDayOrder;
	}

	public void setTripDayOrder(Integer tripDayOrder) {
		this.tripDayOrder = tripDayOrder;
	}

	@Column(name = "TRIP_DESCRIPTION")
	public String getTripDescription() {
		return this.tripDescription;
	}

	public void setTripDescription(String tripDescription) {
		this.tripDescription = tripDescription;
	}

	@Column(name = "STAY_TIME", nullable = false, precision = 53, scale = 0)
	public double getStayTime() {
		return this.stayTime;
	}

	public void setStayTime(double stayTime) {
		this.stayTime = stayTime;
	}

	@Column(name = "SPOT_ORDER", nullable = false)
	public int getSpotOrder() {
		return this.spotOrder;
	}

	public void setSpotOrder(int spotOrder) {
		this.spotOrder = spotOrder;
	}

	@Column(name = "TEMP_TRIP_DETAIL_ID", unique = true, nullable = false, length = 10)
	public String getTempTripDetailId() {
		return this.tempTripDetailId;
	}

	public void setTempTripDetailId(String tempTripDetailId) {
		this.tempTripDetailId = tempTripDetailId;
	}

}
