package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * TripLikeRecord generated by hbm2java
 */
public class TripLikeRecord implements java.io.Serializable {

	private TripLikeRecordId id;

	public TripLikeRecord() {
	}

	public TripLikeRecord(TripLikeRecordId id) {
		this.id = id;
	}

	public TripLikeRecordId getId() {
		return this.id;
	}

	public void setId(TripLikeRecordId id) {
		this.id = id;
	}

}
