package model;

// Generated 2014/9/2 �U�� 08:47:27 by Hibernate Tools 4.0.0

/**
 * TripCollectRecord generated by hbm2java
 */
public class TripCollectRecord implements java.io.Serializable {

	private TripCollectRecordId id;

	public TripCollectRecord() {
	}

	public TripCollectRecord(TripCollectRecordId id) {
		this.id = id;
	}

	public TripCollectRecordId getId() {
		return this.id;
	}

	public void setId(TripCollectRecordId id) {
		this.id = id;
	}

}
